id: P005384
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 11:47:32.628310
source_metadata:
  id: bdr:W175
  title: ངག་དབང་བློ་བཟང་རྒྱ་མཚོའི་རང་རྣམ
  author: ''
  volumes:
    6aa941b9f8cb4666aa6eecfb994b2f2a:
      image_group_id: I4254
      title: ''
      volume_number: 1
      total_pages: 740
      base_file: v001.txt
    ff56994f67544f3880871745ee2fbba9:
      image_group_id: I4255
      title: ''
      volume_number: 2
      total_pages: 550
      base_file: v002.txt
    c4c9dae7bb6c4ff08d4d5839364e2941:
      image_group_id: I4256
      title: ''
      volume_number: 3
      total_pages: 472
      base_file: v003.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
