id: I73055445
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T18:08:39+00:00'
last_modified: '2022-06-08T02:42:10.436329+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W175
  title: ངག་དབང་བློ་བཟང་རྒྱ་མཚོའི་རང་རྣམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    761E:
      image_group_id: I4254
      title: ''
      total_pages: 740
      order: 1
      base_file: 761E.txt
    '4180':
      image_group_id: I4255
      title: ''
      total_pages: 550
      order: 2
      base_file: 4180.txt
    '3197':
      image_group_id: I4256
      title: ''
      total_pages: 472
      order: 3
      base_file: 3197.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
